version: '2'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./storage/mysql:/var/lib/mysql

  php-fpm:
    build:
     context: ./docker/php-fpm
     dockerfile: ubuntu/Dockerfile
#    ports:
#      - "9009:9009"
    volumes:
      - ./:/var/www
      - ./logs/xdebug/:/var/log/xdebug
    links:
      - db

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes_from:
      - php-fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx

#  test:
#    image: debian:jessie-slim
#    tty: true
